global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:

  - job_name: 'node_exporter'

    static_configs:

      - targets: ['3.110.102.195:9100']
      - targets: ['13.235.113.187:9100']
